version: '3.8'

services:

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=prestashop
      - MYSQL_USER=prestashopuser
      - MYSQL_PASSWORD=+QAY2wsx3edc
    volumes:
      - /home/vagrant/datas/volumes:/volumes
      - /home/vagrant/datas/volumes/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - /home/vagrant/datas/volumes/db_data:/var/lib/mysql
    ports:
      - 3307:3306

  prestashop:
    image: prestashop/prestashop
    environment:
      - DB_SERVER=mysql
    ports:
      - 8090:80
    links:
      - mysql
    depends_on:
      - mysql
